var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6","es3");
window.errorsConsole=function(){function a(a){var b="";void 0!==a&&("object"===typeof a&&"error"in a&&a.error&&(a=a.error),"string"!==typeof a&&(a.name?b=a.name.replace("Error",""):a instanceof EvalError?b="Eval":a instanceof RangeError?b="Range":a instanceof ReferenceError?b="Reference":a instanceof SyntaxError?b="Syntax":a instanceof URIError?b="URI":a.type?(b=a.type.charAt(0).toUpperCase()+a.type.slice(1),b=b.replace("Error","")):a.message&&(b=a.message,b=b.replace(/("|'|\||&|\.|,|\(|\)|%)/gi,
""),b=b.replace("Error",""),30<b.length&&(b=b.substring(0,29),a=b.lastIndexOf(" "),0<a&&(b=b.substring(0,a))))));external&&"Exception"in external&&external.Exception(b)}function b(b,d){setTimeout(function(){if(f){var e="";void 0===b?e="undefined error":"object"===typeof b?"stack"in b&&b.stack?("message"in b&&b.message&&(e+=b.message+"\r\n"),e+=b.stack):"message"in b&&b.message?(e=b.message,"filename"in b&&b.filename&&(e+='<div class="error__item__file">'+b.filename),"lineno"in b&&b.lineno&&(e+=":"+
b.lineno),"columnNumber"in b&&b.columnNumber&&(e+=":"+b.columnNumber),e+="</div>"):e="type"in b&&b.type?b.type:b:e=b;d&&(e+=". Module: "+d);c(e)}external&&"Exception"in external&&a(b)},10)}function c(a){void 0===a&&(a="undefined error");if(a){var b=document.createElement("div");b.className="error__item";b.innerHTML="object"==typeof a&&"stack"in a&&a.stack?a.stack:a;e.parentNode||document.body.appendChild(e);e.insertBefore(b,e.firstChild);(function(a){setTimeout(function(){e.removeChild(a)},5E3)})(b)}}
function d(a){a=a||window.event;b(a);a.preventDefault&&a.preventDefault();return!0}var e=document.createElement("div"),f=!1;return{Init:function(){e.className="error";window.attachEvent?window.attachEvent("onerror",d):window.addEventListener?window.addEventListener("error",d):window.onerror=d},Add:b,Render:c,SendErrorTrack:a,Toggle:function(){f=!f}}}();errorsConsole.Init();errorsConsole.Toggle();window.addClass=function(a,b){if(!a||!b)return!1;if(a.classList)a.classList.add(b);else{var c=a.className;c=c?a.className.split(" "):[];for(var d=[],e=0,f=c.length;e<f;++e)c[e]!==b&&d.push(c[e]);d.push(b);a.className=d.join(" ")}};window.removeClass=function(a,b){if(a&&b)if(a.classList)a.classList.remove(b);else{var c=a.className;c=c?a.className.split(" "):[];for(var d=[],e=0,f=c.length;e<f;++e)c[e]!==b&&d.push(c[e]);a.className=d.join(" ")}};
window.jsonParse=function(a,b){if(!a)return null;try{return window.JSON?JSON.parse(a):eval("("+a+")")}catch(c){try{return eval("("+a+")")}catch(d){return window.errorsConsole&&window.errorsConsole.SendErrorTrack(d),{dataError:"Error processing data"+(b?" ("+b+")":"")+". Please try again later."}}}};
window.jsonStringify=function(a){if(window.JSON)return JSON.stringify(a);for(var b="[",c=0,d=a.length;c<d;c++){b+="{";for(var e in a[c])a[c].hasOwnProperty(e)&&(b+='"'+e+'": '+a[e]+", ");b+="},"}return b+"]"};window.indexOfArray=function(a,b){if(!a||!b)return-1;if("object"!==typeof a)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};
window.querySelectorAllFn=function(a,b){if(document.querySelectorAll)return a.querySelectorAll(b);var c=document.createElement("style");a=[];document.documentElement.firstChild.appendChild(c);document._qsa=[];c.styleSheet.cssText=b+"{x-qsa:expression(document._qsa && document._qsa.push(this))}";window.scrollBy(0,0);for(c.parentNode.removeChild(c);document._qsa.length;)b=document._qsa.shift(),b.style.removeAttribute("x-qsa"),a.push(b);document._qsa=null;return a};
window.formatDateInString=function(a,b){b=b||"";var c=a.getFullYear()+b;10>a.getMonth()+1&&(c+="0");c+=""+(a.getMonth()+1)+b;10>a.getDate()&&(c+="0");return c+=""+a.getDate()};window.priceToString=function(a){a=parseFloat(a,10);a=a.toFixed(2);a=a.split(".");var b=a[0];a=a[1];a=0===parseInt(a,10)?"":"."+a;1E3<=Math.abs(parseInt(b,10))&&(b=b.replace(/\B(?=(\d{3})+(?!\d))/g," "));return b+a};
window.roundDemicalPlaces=function(a,b){null===b&&(b=2);a=parseFloat(a,10);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};window.addEventListenerFn=function(a,b,c,d){a&&(a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,d?d:!1))};window.removeEventListenerFn=function(a,b,c){a&&(a.detachEvent?a.detachEvent("on"+b,c):a.removeEventListener&&a.removeEventListener(b,c,!1))};
window.arrayEquals=function(a,b){if(!b||a.length!=b.length)return!1;for(var c=0,d=a.length;c<d;c++)if(a[c]instanceof Array&&b[c]instanceof Array){if(!window.arrayEquals(a[c],b[c]))return!1}else if(window.jsonStringify(a[c])!=window.jsonStringify(b[c]))return!1;return!0};window.trimFn=function(a){return a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")};
window.throttle=function(a,b,c){var d,e,f,g=null,h=0;c||(c={});var l=function(){h=!1===c.leading?0:Date.now();g=null;f=a.apply(d,e);g||(d=e=null)};return function(){var m=Date.now();h||!1!==c.leading||(h=m);var n=b-(m-h);d=this;e=arguments;0>=n||n>b?(g&&(clearTimeout(g),g=null),h=m,f=a.apply(d,e),g||(d=e=null)):g||!1===c.trailing||(g=setTimeout(l,n));return f}};
window.debounce=function(a,b,c){var d;return function(){var e=this,f=arguments,g=c&&!d;clearTimeout(d);d=setTimeout(function(){d=null;c||a.apply(e,f)},b);g&&a.apply(e,f)}};var Constants={Init:function(a){switch(a){case 4:Constants.TradeAction="Buy;Sell;Balance;Credit;Buy Limit;Sell Limit;Buy Stop;Sell Stop".split(";");Constants.OrderType="Buy;Sell;Buy Limit;Sell Limit;Buy Stop;Sell Stop".split(";");break;case 5:Constants.TradeAction=["Buy","Sell","Balance",null,"Credit",null,"Charge","Correction","Bonus","Comission","Comission Daily","Comission Monthly","Agent Monthly","Interestrate","Buy Cancelled","Sell Cancelled"],Constants.OrderType="Buy;Sell;Buy Limit;Sell Limit;Buy Stop;Sell Stop;Buy Stop Limit;Sell Stop Limit".split(";")}},
TradeMode:["Real","Demo"]};var isOldBrowser=function(){var a=navigator.userAgent;return 0<=a.indexOf("MSIE 8")||0<=a.indexOf("MSIE 7")||0<=a.indexOf("MSIE 6")||0<=a.indexOf("MSIE 5")?!0:!1}();function $(a){return document.getElementById(a)}function StopWatch(a){var b=a,c=new Date,d=new Date;this.Start=function(){b=!0;c=new Date};this.Reset=function(){};this.Stop=function(){b=!1};this.GetElapsedMilliseconds=function(){return b?new Date-c:d-c}}
var Helpers={Incrementor:0,NextInt:function(){return++Helpers.Incrementor},DumpObjects:function(a,b){for(var c=0;c<a.length;c++){var d=document.createElement("LI"),e=[],f;for(f in a[c])e.push(f+": "+a[c][f]);d.innerHTML="{ "+e.join(", ")+" }";b.appendChild(d)}},DaysBetween:function(a,b){a=a.getTime();return(b.getTime()-a)/864E5},FormatTimeElapsed:function(a){if(!a)return"0";a=Math.round(a);if(60>a)return Localization.Get(Helpers.formatMany(a,"ofseconds"),[a]);a=Math.round(a/60);if(60>a)return Localization.Get(Helpers.formatMany(a,
"ofminutes"),[a]);a=Math.round(a/60);if(24>a)return Localization.Get(Helpers.formatMany(a,"ofhours"),[a]);a=Math.round(a/24);return Localization.Get(Helpers.formatMany(a,"ofdays"),[a])},formatMany:function(a,b){a=10>a?a:a%(10*Math.floor(a/10));return 1==a?b+"X1":2==a||3==a||4==a?b+"X2":b},FormatMoney:function(a){return a?995>=a?a.toFixed(0):1050>=a?"1K":9950>=a?(a/1E3).toFixed(50>a%1E3||950<a%1E3?0:1)+"K":999500>=a?(a/1E3).toFixed(0)+"K":105E4>=a?"1M":995E4>=a?(a/1E6).toFixed(5E4>a%1E3||95E4<a%1E3?
0:1)+"M":(a/1E6).toFixed(0)+"M":"0"},FormatThousands:function(a){return 1E3>Math.abs(a)?a:a.toString().replace(/\B(?=(\d{3})+(?!\d))/g," ")},ConvertUnixTime:function(a,b){return Helpers.FormatDate(new Date(1E3*a),b)},ConvertUnixTimeAddMonth:function(a,b){a=new Date(1E3*a);a=new Date((new Date(a)).setMonth(a.getMonth()+1));return Helpers.FormatDate(a,b)},FormatDate:function(a,b){var c=a.getFullYear()+".";9>a.getMonth()&&(c+="0");c+=a.getMonth()+1+".";10>a.getDate()&&(c+="0");c+=a.getDate();b&&(c+=
" ",10>a.getHours()&&(c+="0"),c+=a.getHours()+":",10>a.getMinutes()&&(c+="0"),c+=a.getMinutes());return c},RoundScaleMax:function(a){var b=0==a?0:Math.floor(Math.log(a)/Math.LN10),c=Math.pow(10,b);a=Math.ceil(a/c);var d=5>a&&1<b?Math.floor(c)/2:Math.floor(c);1<=b&&(2>a?d/=4:4>a?d/=2:6<a&&(d*=2));return{max:a*Math.floor(c),step:d}},ClearTableBody:function(a){if(a&&a.parentNode){var b=document.createElement("TBODY");b.id=a.id;a.parentNode.replaceChild(b,a);return b}return a},UserLink:function(a){return'<a href="javascript:void(false);" onclick="external.OpenUrl(\'https://www.mql5.com/'+
Localization.GetDefaultLanguageMql5()+"/users/"+a+'\');" title="'+a+'">'+a+"</a>"},UserLinkFull:function(a,b){return'<a href="javascript:void(false);" onclick="external.OpenUrl(\'https://www.mql5.com/'+Localization.GetDefaultLanguageMql5()+"/users/"+a+'\');" title="'+a+'">'+b+"</a>"},SignalLink:function(a,b){a="https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+"/signals/"+a;return'<a href="javascript:void(false);" onclick="external.OpenUrl(\''+a+'\');" title="'+a+'">'+b+"</a>"},Class:function(a,
b,c){if(a.className){var d=a.className.split(" "),e;var f=0;for(e=d.length;f<e;++f)if(d[f]==b){c&&(d.splice(f,1),a.className=d.join(" "));return}c||(d.push(b),a.className=d.join(" "))}else c||(a.className=b)},HashCode:function(a){for(var b=5381,c=0;c<a.length;c++){var d=a.charCodeAt(c);b=(b<<5)+b+d}return b},GetHashIdByUrl:function(a){return a?("i_"+Helpers.HashCode(a)).replace("-","m"):"i_m00"}},ieVersion=function(){var a=3,b=document.createElement("div"),c=b.getElementsByTagName("i");do b.innerHTML=
"\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e";while(c[0]);return 4<a?a:void 0}(),ieOlderThan9=ieVersion&&9>ieVersion;function showData(a){var b=document.createElement("textarea");b.style.position="fixed";b.style.zIndex="9999";b.style.top="20";b.style.left="20";document.body?document.body.appendChild(b):setTimeout(function(){document.body.appendChild(b)},300);b.value=a}function GetPriceWithVat(a){return vat&&0<vat?a+vat/100*a:a};var Localization={Translates:{},GetTranslates:function(){var a=external.GetTranslate();if(!a)return{};a=jsonParse(a,1);return!a||"dataError"in a?{}:a},GetDefaultLanguage:function(){try{return"ru"==external.GetLanguageMql5()?"ru":"en"}catch(a){return"en"}},GetDefaultLanguageMql5:function(){try{return external.GetLanguageMql5()||"en"}catch(a){return"en"}},Get:function(a,b){var c=null;a in this.Translates&&this.Translates[a]&&(c=this.Translates[a]);c||(c="["+a+"]");if(c&&b&&b.length&&0<b.length)for(a=
0;a<b.length;a++)c=c.replace("{"+a+"}",b[a]);return c},GetTooltip:function(a,b){b=null;a="t_"+a;a in this.Translates&&this.Translates[a]&&(b=this.Translates[a]);b||(b="["+a+"]");return b},Apply:function(){for(var a=document.getElementsByTagName("VAR"),b=0;b<a.length;b++)if("translated"!=a[b].className){var c=a[b].innerHTML;c&&(a[b].innerHTML=Localization.Get(c),Localization.Translates["t_"+c]&&a[b].parentNode&&("STRONG"==a[b].parentNode.tagName&&a[b].parentNode.parentNode?a[b].parentNode.parentNode.title=
Localization.GetTooltip(c):a[b].parentNode.parentNode&&"LI"==a[b].parentNode.parentNode.tagName?a[b].title=Localization.GetTooltip(c):a[b].parentNode.title=Localization.GetTooltip(c)))}}};Localization.Translates=Localization.GetTranslates();Localization.GetTranslates=void 0;function SignalsPaymentSystem(a){var b=Localization;this.RenderPaymentSystem=function(c,d,e,f){var g=document.getElementById("paymentSystemListBlock");g&&g.parentNode.removeChild(g);(g=document.getElementById("paymentSystemMessageBlock"))&&g.parentNode.removeChild(g);g=document.createElement("div");g.id="paymentSystemListBlock";Helpers.Class(g,"payments");var h="<div id='paymentSystemList'><div class='payment-info'>";d.subscription_allowance&&(h=h+"<div class='signal-warnings__list'>"+Details.RenderWarnings(d),
h+="</div>");var l=[];if(Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id!=d.id)h+=this.RenderNotpayment(d);else{var m=this.GetProductInfo(d,"renew"==f,!0,!0);h+=m.html;if(!("GetPaymentSystemsHtml"in external)){var n=a.GetPaymentsSystem();if(!n||!n.payment_methods||0>=n.count)return;h+="<div class='paymetns__choosen'>"+b.Get("payment_choose_system")+"</div>"}h+='<div class="paymetns__payment-list" id="paymentList">';if(!(d.subscription_allowance||"GetPaymentSystemsHtml"in external))for(m=
0;m<n.payment_methods.length;m++){var k=n.payment_methods[m];var p=d,t=e,r=f,v=l,w=external.GetBalance();"mql5"==k.name&&user_login&&(0==w||w<p.price)?k="":ieOlderThan9&&"epayments"==k.name?k="":ieOlderThan9&&"commercegate"==k.name?k="":(w="<div class='payment-button' id='payment_"+k.name+"'>",p={url_redirect:k.url_redirect,product_id:p.id,product_price:p.price,type:parseInt(t,10),typebuy:r,platform:platform,payment_title:k.title,payment_name:k.name,payment_additional_check:k.additional_check},w+=
"<a class='payment-button__img' title='"+k.title+"' href='javascript:void(0);'",w+=">",t=Helpers.GetHashIdByUrl(k.logo),w+="<img alt='"+k.title+"' class='"+t+"' src='"+k.logo+"' onclick='Signals.PaymentSystem.PaymentButtonClick("+jsonStringify(p)+");'>",w+="</a></div>",v.push({src:k.logo,imageName:t}),k=w);h+=k}n=h+"</div>";(m=b.Get("signals_agree_rules"))&&(m=m.replace("<a>",'<a href="javascript:void(false);" onclick="external.OpenUrl(\'https://www.mql5.com/'+b.GetDefaultLanguageMql5()+"/signals/rules');\">"));
h=b.Get("purchase_rules_gdpr");h=h.replace("<a href={0}>",'<a href="javascript:void(false);" onclick="external.OpenUrl(\'https://www.mql5.com/'+b.GetDefaultLanguageMql5()+"/about/terms');\">");h=h.replace("<a href={1}>",'<a href="javascript:void(false);" onclick="external.OpenUrl(\'https://www.mql5.com/'+b.GetDefaultLanguageMql5()+"/about/terms#part_12');\">");k=b.Get("purchase_admonition");h=n+('<div class="paymetns__rules"><div class="rules-admonition">'+k+"</div><p>"+m+"</p><p>"+h+"</p></div>")}g.innerHTML=
h+"</div></div>";removeClass(c,"hidden");c.appendChild(g);!d.subscription_allowance&&"GetPaymentSystemsHtml"in external&&external.GetPaymentSystemsHtml(d.id,parseInt(e,10),f);l&&0<l.length&&setImgesSrcAsync(l)};this.RenderNotpayment=function(a){var c="";Signals.CurrentSubscription&&Signals.CurrentSubscription.signal&&(c=Signals.CurrentSubscription.signal.name);var e="";a&&(e=a.name);a="";Signals.CurrentAccount&&(a=Signals.CurrentAccount.account_login);var f="<div class='clean'></div><div class='subscribe-result'>"+
('<h1 class="subscribe-result__title">'+b.Get("payment_not_pay_title").replace("{0}",c)+"</h1>");f+='<div class="subscribe-result__desc"><p>'+b.Get("payment_not_pay_description").replace("{0}",a).replace("{1}",c).replace("{2}",e).replace("{3}",c)+"</p></div>";f+='<div class="subscribe-result__promo"><p>'+b.Get("connect_vps_description")+"</p></div>";f+='<a href="javascript:void(false);" onclick="external.OpenVps()" class="button button_big">'+b.Get("connect_vps")+"</a>";return f+"</div>"};this.PaymentComplete=
function(a,d){Signals.PaymentCompleteResult={success:a,result:d};var c=document.getElementById("paymentSystemListBlock");c&&c.parentNode.removeChild(c);var f=document.getElementById("signal_details_payment");if(f){c=document.getElementById("paymentSystemMessageBlock");c||(c=document.createElement("div"),c.id="paymentSystemMessageBlock",c.className="subscribe-result",f.appendChild(c));removeClass(f,"hidden");(f=document.getElementById("signal_details_statistics"))&&Helpers.Class(f,"hidden");f="";if(a){Signals.InitSubscription();
var g=Signals.CurrentSubscription;d=Signals.CurrentAccount;a=g&&g.subscription?2764800<g.subscription.date_expiration-g.subscription.date_start:null;g&&g.signal&&(f+='<h1 class="subscribe-result__title subscribe-result__title_with-info"><i class="icon-success"></i>'+b.Get(a?"successfully_renewal_title":"successfully_subscribed_title",[g.signal.name])+"</h1>");g&&g.subscription&&(f=f+'<div class="subscribe-result__info">'+('<div class="subscribe-result__price">'+(0<g.subscription.price?g.subscription.price.toFixed(2)+
" USD":'<span class="green">'+b.Get("free")+"</span>")+"</div>"),f+='<div class="subscribe-result__interval">'+b.Get("subscribed_interval",[Helpers.ConvertUnixTime(g.subscription.date_start,!0),Helpers.ConvertUnixTime(g.subscription.date_expiration,!0)])+"</div>",f+="</div>");f+='<div class="subscribe-result__sub-title subscribe-result__sub-title_with-info">'+b.Get("subscribe_success_2").replace("<a>",'<a href="javascript:void(false);" onclick="Details.SwitchToStatistics();">')+"</div>";f+='<div class="subscribe-result__desc">';
a="https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+"/articles/618?utm_campaign=MetaTrader+"+platform+"+Terminal&utm_medium=special&utm_source=Signal+subscribe+success";f+="<p>"+b.Get("subscribe_success_3",[d.account_login,d.broker]).replace("<a>",'<a href="javascript:void(false);" onclick="external.OpenUrl(\''+a+"');\">")+"</p>";f=f+"</div>"+('<div class="subscribe-result__promo"><p>'+b.Get("connect_vps_description")+"</p></div>");f+='<a href="javascript:void(false);" onclick="external.OpenVps()" class="button button_big">'+
b.Get("connect_vps")+"</a>";Details.UpdateTopButtons();Details.FillSidebarButtons(Details.Existing)}else a=(a=Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id==Details.Current.id)?"renew_failed":"subscribe_failed_title",d&&d.error?(0>d.error.indexOf("<h1")&&(f+='<h1 class="subscribe-result__title subscribe-result__title_error">'+b.Get(a)+"</h1>"),f=f+"<div class='subscribe-result__sub-title'>"+d.error,f+="</div>"):f='<h1 class="subscribe-result__title subscribe-result__title_error">'+
b.Get(a)+"</h1></div>";$("signal_popup_close").setAttribute("href","javascript:Details.TogglePayments(false)");c.innerHTML=f}};this.GetProductInfo=function(a,d,e,f){d=external.GetSubscribeData(d?1:0);d=jsonParse(d,7);f='<div class="subscribe-details"><dl>'+("<dt>"+b.Get("signal")+":</dt>");f+="<dd>"+Helpers.SignalLink(a.id,d.signal)+"</dd>";f+="<dt>"+b.Get("author")+":</dt>";f+="<dd>"+Helpers.UserLinkFull(d.provider_login,d.provider)+"</dd>";f+="<dt>"+b.Get("broker")+":</dt>";f+="<dd>"+d.broker+"</dd>";
f+="<dt>"+b.Get("growth")+":</dt>";f+="<dd>"+d.growth+"%</dd>";f+="<dt>"+b.Get("date")+":</dt>";f+="<dd>"+Helpers.ConvertUnixTime(d.from,!0)+" - "+Helpers.ConvertUnixTime(d.to,!0)+"</dd>";if(vat&&0<vat&&"price"in a&&0<a.price){f+="<dt>"+b.Get("price")+":</dt>";if(Signals.ShowDailyPrice){var c=a.price/30;c=window.priceToString(c);c=parseFloat(c)+" USD";var h=b.Get("per_day");h=h.replace("{0}",c);f+="<dd>"+window.priceToString(a.price)+' USD <span class="subscribe-details_per-day">('+h+")</span></dd>"}else f+=
"<dd>"+window.priceToString(a.price)+" USD</dd>";f+="<dt>"+b.Get("vat").replace("{0}",vat)+":</dt>";f+="<dd>"+window.priceToString(vat/100*a.price)+" USD</dd>";f+="<dt>"+b.Get("total")+":</dt>";f+="<dd>"+window.priceToString(GetPriceWithVat(a.price))+" USD</dd>"}f+="</dl></div>";a=!0;if(e){if(d.errors&&0<d.errors.length){f+="<div class='messageError'>";for(e=0;e<d.errors.length;e++)f+="<p>"+d.errors[e]+"</p>";f+="</div>";a=!1}if(d.warnings&&0<d.warnings.length){f+="<div class='messageWarning'>";for(e=
0;e<d.warnings.length;e++)f+="<p>"+d.warnings[e]+"</p>";f+="</div>"}}return{html:f,allowed:a}};this.GetUnsubscribeProductInfo=function(a){var c=jsonParse(external.GetSubscription(),3);var e="<div class='subscribe-details'><dl>"+("<dt>"+b.Get("signal")+":</dt>");e+="<dd>"+Helpers.SignalLink(a.id,a.name)+"</dd>";e+="<dt>"+b.Get("author")+":</dt>";e+="<dd>"+Helpers.UserLinkFull(a.author_login,a.author_name)+"</dd>";e+="<dt>"+b.Get("broker")+":</dt>";e+="<dd>"+a.broker+"</dd>";e+="<dt>"+b.Get("growth")+
":</dt>";e+="<dd>"+a.gain+"%</dd>";e+="<dt>"+b.Get("date")+":</dt>";e=c.subscription&&"date_start"in c.subscription&&"date_expiration"in c.subscription?e+("<dd>"+Helpers.ConvertUnixTime(c.subscription.date_start,!0)+" - "+Helpers.ConvertUnixTime(c.subscription.date_expiration,!0)+"</dd>"):e+"<dd></dd>";e+="</dl></div>";c.subscription&&"price"in c.subscription&&0<c.subscription.price&&(e+="<div class='messageWarning'>"+b.Get("unsubscribe_charge_warning",[c.subscription.price])+"</div>");return e};
this.PaymentButtonClick=function(a){if(Signals.PaymentSystem.IsLogined()){var b=[a.url_redirect];-1==a.url_redirect.indexOf("?")?b.push("?"):b.push("&");b.push("language=");b.push(encodeURIComponent(external.GetLanguage()));b.push("&id=");b.push(a.product_id);b.push("&type=");b.push(a.type);b.push("&typebuy=");b.push(a.typebuy);b.push("&data=");b.push(encodeURIComponent(external.GetAuthorization()));b.push("&r=");b.push(Math.random(2,9999999));b.push("&signalmt=");b.push(a.platform);b.push("&signallogin=");
b.push(Signals.CurrentAccount.account_login);b.push("&signalbroker=");b.push(encodeURIComponent(encodeURIComponent(Signals.CurrentAccount.broker)));b.push("&signaltype=");b.push(Signals.CurrentAccount.acc_type);b.push("&signalstate=");b.push(Signals.CurrentAccount.signal);b.push("&signalflags=");b.push(Signals.CurrentAccount.flags);var c=document.getElementById("agreementRenew");c&&(b.push("&agreementrenew="),b.push(c.checked?1:0));external.PurchasedLog(0,a.payment_title,a.product_id,a.product_price);
external.Purchase(b.join(""),a.payment_additional_check,a.payment_name,a.product_id.toString(),a.type,a.typebuy);Signals.PaymentSystem.GrayBackground(a.element_id?a.element_id:"payment_"+a.payment_name)}};this.RenderPasswordForm=function(a,d){var c="<div class='pass-item'><div class='text-pass'>"+b.Get("enter_password")+":</div><div class='input-text'><input type='password' name='user_password' id='user_password' autocomplete='off'></div></div>";return c+="<div class='pass-item' style='margin-top: 15px;'><div class='text-pass'>&nbsp;</div><div style='margin-left:155px;'><a class='button static blue' style='width:140px;' id='user_password_button' href='javascript:void()' onclick='return Signals.PaymentSystem.CheckPasswordActivation("+
a.id+',"'+d+"\");'>"+b.Get(d)+"</a></div></div>"};this.CheckPasswordActivation=function(a,d){var c=document.getElementById("user_password"),f=document.getElementById("user_error");if(!c||!f)return!1;user_login=external.GetLogin();if(""!=user_login&&!external.CheckPassword(c.value))return f.innerHTML=b.Get("error_user_password"),f.style.display="",!1;f.style.display="none";"renew"==d?Signals.Renew(null,a):Signals.Subscribe(null,a);Details.TogglePayments(!1,!1,!1);Details.UpdateTopButtons();Details.FillSidebarButtons(Details.Existing);
return!1};this.SubscribeNow=function(a,b){"renew"==b?Signals.Renew(null,a):Signals.Subscribe(null,a);Details.TogglePayments(!1,!1,!1);Details.FillSidebarButtons(Details.Existing);Details.UpdateTopButtons();return!1};this.CheckKeySubmitForm=function(a){a=a||window.event;return 13==a.keyCode?((a=document.getElementById("user_password_button"))&&a.click(),!1):!0};this.GrayBackground=function(a){var b=document.getElementById("paymentSystemList");b&&(b.style.opacity="0.25",b.style.backgroundColor="#fff",
b.style.zIndex=10);if(b=document.getElementById("paymentSystemListBlock")){for(var c=b.getElementsByTagName("a"),f=0;f<c.length;f++)if("payment-button__img"==c[f].className){c[f].disabled="true";try{c[f].style.pointerEvents="none"}catch(g){}}c=document.createElement("div");c.className="loading-img-page";c.id="loadImgPay";c.style.position="absolute";c.style.margin="0 auto";c.style.padding="0px 0px";c.style.opacity=1;c.style.zIndex=99;if(a=document.getElementById(a))f=a.offsetLeft,c.style.top=a.offsetTop+
16+"px",c.style.left=f+60+"px",c.innerHTML="<div><img src='loading.gif?r="+Math.random(2,9999999)+"' id='loadingImg' /></div>",b.appendChild(c)}};this.ClosePayWindow=function(){var a=document.getElementById("loadImgPay");a&&a.parentNode.removeChild(a);if(a=document.getElementById("paymentSystemList")){for(var b=a.getElementsByTagName("a"),e=0;e<b.length;e++)if("payment-button__img"==b[e].className){b[e].disabled="false";try{b[e].style.pointerEvents=""}catch(f){}}a.style.opacity="100.0"}};this.CancelImagesDownload=
function(){external.CancelImageDownloads()};this.IsLogined=function(){return""==external.GetLogin()&&(external.GetOptions(),""==external.GetLogin())?!1:!0};this.RenderViewConfirmUnsibscibe=function(a,d){var c=document.getElementById("paymentSystemListBlock");c&&c.parentNode.removeChild(c);(c=document.getElementById("paymentSystemMessageBlock"))&&c.parentNode.removeChild(c);c=document.createElement("div");c.id="paymentSystemListBlock";Helpers.Class(c,"payments");var f="<div id='paymentSystemList'><div class='payment-info'>"+
("<h1 class='green' style='margin-bottom:15px;'>"+b.Get("unsibscribe_view_title")+"</h1>");f+=this.GetUnsubscribeProductInfo(d);f=f+"<div class='messageError' style='display:none' id='user_error'></div><div class='check-pass'><div></div><div class='pass-item' style='margin-top: 15px;'><div class='text-pass'>&nbsp;</div><div style='margin-left:155px;'>"+("<a class='button button_red static' style='width:140px;' id='user_agree_unsibscribe' href='javascript:void()' onclick='Signals.Unsubscribe(event,"+
d.id+"); return false;'>"+b.Get("unsubscribe")+"</a>");f+="<a class='button button_white-bg-green static' style='width:140px;margin-left:15px;' id='user_agree_unsibscribe' href='javascript:void()' onclick='Signals.Select(event,"+d.id+"); return false;'>"+b.Get("cancel")+"</a>";c.innerHTML=f+"</div></div><div class='pass-item' style='margin-top: 15px;'><div class='text-pass'>&nbsp;</div><div style='margin-left:155px;'></div></div></div></div></div>";a.appendChild(c);if(a=document.getElementById("user_password"))a.onkeydown=
this.CheckKeySubmitForm}};var Signals={SubscribeMode:!1,UnsubscribeMode:!1,PaymentsMessageMode:!1,PaymentCompleteResult:!1,Synchronized:!0,Ready:!1,FLAG_NONPUBLIC:2,FLAG_NONSUBSCRIBABLE:4,FLAG_NONRENEWABLE:8,ShowDailyPrice:!0,InitSubscription:function(){Signals.CurrentSubscription=Signals.GetSubscription()},InitAccount:function(){Signals.CurrentAccount=Signals.GetAccountInfo()},Fetch:function(a){a=external.GetSignals(a.from,a.count,a.sort,a.price);return jsonParse(a,6)},FetchStatistics:function(a){a=external.GetStatistics(a.sort,
"");return jsonParse(a,5)}};Signals.LoadingBar=function(){var a=document.createElement("div");a.className="loading-bar";var b=document.createElement("div");a.className="loading-bar__substrate";a.appendChild(b);var c=document.createElement("img");c.className="loading-bar__spinner";a.appendChild(c);return{Show:function(){c.setAttribute("src","loading.gif?r="+Math.random(2,9999999));document.body&&document.body.appendChild(a)},Hide:function(){a.parentNode&&a.parentNode.removeChild(a)}}}();
Signals.Select=function(a,b,c,d,e){a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0);a&&a.preventDefault&&a.preventDefault();c?Signals.SubscribeMode=!0:d&&(Signals.UnsubscribeMode=!0);e&&(Signals.PaymentsMessageMode=!0);if(!Signals.Synchronized)if(Details.Existing&&Details.Existing.id==b)Details.ShowAsIs();else{try{Signals.LoadingBar.Show();var f=external.GetSignal(b,Details.GetChartWidth(),Details.GetChartHeight());f&&ShowSignal(b,f)}catch(g){errorsConsole.Add(g),ShowSignal(b)}setTimeout(function(){Signals.LoadingBar.Hide()},
5E3)}};Signals.Preload=function(a){Signals.Synchronized||Details.Existing&&Details.Existing.id==a||(Signals.Preloading=!0,external.GetSignal(a,Details.GetChartWidth(),Details.GetChartHeight())&&(Signals.Preloading=!1))};
Signals.SelectStatistics=function(a,b,c,d,e){if(!Signals.Synchronized){e&&(Signals.SubscribeMode=!0);try{var f=external.GetStatisticsDetail(b,c,d,Statistics.GetChartWidth(),Statistics.GetChartHeight());f&&ShowStatistics(b,c,d,f)}catch(g){errorsConsole.Add(g),ShowStatistics(b,c,d)}a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0)}};
Signals.Subscribe=function(a,b){if(!b)if(Details.Current)b=Details.Current.id;else if(Statistics.Current)b=Statistics.Current.signal_id;else return;external.Subscribe(b);a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0)};Signals.Renew=function(a,b){if(!b)if(Details.Current)b=Details.Current.id;else if(Statistics.Current)b=Statistics.Current.signal_id;else return;external.Renew(b);a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0)};
Signals.Unsubscribe=function(a,b){if(!b)if(Details.Current)b=Details.Current.id;else if(Statistics.Current)b=Statistics.Current.signal_id;else return;external.UnSubscribe(b);a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0)};Signals.FavoritesFetch=function(){var a=external.GetFavorites();a=jsonParse(a,4);return"favorites"in a?a.favorites:[]};Signals.FavoritesAdd=function(a){external.FavoritesAdd(a)};Signals.FavoritesDelete=function(a){external.FavoritesDelete(a)};
Signals.GetSubscription=function(){var a=external.GetSubscription();return(a=jsonParse(a,3))&&a.signal&&a.signal.id?a:null};Signals.GetAccountInfo=function(){var a=external.GetAccountInfo();return(a=jsonParse(a,9))&&a.account?a.account:null};Signals.SetSynchronized=function(a){a?(document.documentElement.style.cursor="wait !important",Signals.Synchronized=!0):(document.documentElement.style.cursor="auto",Signals.Synchronized=!1)};
Signals.Visualize=function(a){if(!a){if(!Details.Current)return!1;a=Details.Current.id}external.Visualize(a);return!0};Signals.GetPaymentsSystem=function(){try{var a=external.GetPaymentsSystem();if(a)return eval("("+a+")")}catch(b){errorsConsole.Add(b)}return{}};var Charts=Charts||{};
Charts.RenderAvatarNew=function(a,b,c,d,e){var f;if(void 0==a||null==a||void 0==a.className)return!1;var g=document.createElement("CANVAS");g.width=c;g.height=d;if(!g.getContext)return!1;var h="rgb(17,119,219)",l="rgb(206,10,10)",m="rgba(124,204,255,0.25)",n="rgba(185,32,36,0.25)";e&&(h="rgb(193,193,193)",l="rgb(153,153,153)",n=m="rgba(229,229,229,0.25)");e=g.getContext("2d");e.width=c;e.height=d;e.beginPath();var k=(d+1)/4;for(var p=k-.5;p<c;p+=k)e.moveTo(p,0),e.lineTo(p,d);for(p=k-.5;p<d;p+=k)e.moveTo(0,
p),e.lineTo(c,p);e.lineWidth=1;e.setLineDash?(e.strokeStyle="rgb(220,220,220)",e.setLineDash([1]),e.stroke(),e.closePath(),e.setLineDash([])):(e.strokeStyle="rgb(240,240,240)",e.stroke(),e.closePath());p=[];var t=0;var r=100;var v=0;for(f=0;f<b.length;f++){k=b[f];if(isNaN(k))break;p.push(k-100);0!=k&&k<r&&(r=k);k>v&&(v=k);0==k&&0==t&&(t=p.length-1);0!=k&&(t=0)}b=0==t?p.length:t;t=1*c/(b-1);v=(d-2)/100;var w=100<r?0:Math.round(v*(100-r)),q=d-w;e.beginPath();k=q-p[0]*v;var x=.5;e.moveTo(x,q);e.lineTo(x,
k-1.5);var z=k>q?-1:1;var u=k;for(var A=1;A<b;A++){k=q-p[A]*v;x+=t;f=k-.5;r=k>q?-1:1;if(r!=z&&1<A){var y=x-t;var B=u-.5-q;var C=x;u=f-q;u=-B*(C-y)/(u-B)+y;y=q;e.lineTo(u,y);e.fillStyle=0>z?n:m;e.fill();e.closePath();e.beginPath();e.moveTo(u,y)}e.lineTo(x,f);u=k;z=r}e.lineTo(x,q);e.fillStyle=0>z?n:m;e.fill();e.stroke();e.closePath();0<w&&w<d&&(e.beginPath(),e.moveTo(0,q-.5),e.lineTo(c,q-.5),e.strokeStyle="rgb(155,155,155)",e.stroke(),e.closePath());e.beginPath();q=d-1-w;k=q-p[0]*v;x=.5;e.moveTo(x,
k-.5);z=k>q?-1:1;u=k;for(A=1;A<b;A++)k=q-p[A]*v,x+=t,f=k-.5,r=k>q?-1:1,r!=z&&1<A&&(y=x-t,B=u-.5-q,C=x,u=f-q,u=-B*(C-y)/(u-B)+y,y=q,e.lineTo(u,y),e.strokeStyle=0>z?l:h,e.stroke(),e.closePath(),e.beginPath(),e.moveTo(u,y)),e.lineTo(x,f),u=k,z=r;e.strokeStyle=0>z?l:h;e.stroke();if(a.firstChild&&"CANVAS"==a.firstChild.tagName)return!0;a.appendChild(g);return!0};
Charts.RenderAvatarOld=function(a,b,c,d){if(!a)return!1;a.className="histogram";var e=[];var f=1;var g=0;for(var h,l=[],m=100,n=0,k=0;k<b.length;k++)h=b[k],l.push(h-100),0!=h&&h<m&&(m=h),h>n&&(n=h),0==h&&0==g&&(g=l.length-1),0!=h&&(g=0);if(m>n)return!1;b=0==g?b.length:g;k=Math.floor((c+1)/3);c=Math.floor(b/k)||1;d=(d-2)/100;m=100<m?0:d*(100-m);k=b*c-k;0>k&&(k=0);if(0<c&&0<=k)for(;k<b;k+=c)g=l[k]*d,0<g?e.push("<div class='u' style='left: "+f+"px; height: "+g+"px; bottom: "+m+"px;'></div>"):(g*=-1,
e.push("<div class='d' style='left: "+f+"px; height: "+g+"px; bottom: "+(m-g)+"px;'></div>")),f+=3;a.innerHTML+=e.join("");return!0};var List={ChartsQueue:[],FetchPosition:0,FETCH_PORTION:20,CurrentSection:""};List.SignalsParameters={header:"signals-header",from:List.FetchPosition,count:List.FETCH_PORTION,sort:"rating_asc",price:"all"};List.StatisticsParameters={header:"statistics-header",sort:"date_desc"};List.Favorites=[];List.USE_CANVAS=document.createElement("CANVAS").getContext;List.Init=function(a){a=a||"all";Signals.SetSynchronized(!0);List.Favorites=Signals.FavoritesFetch();List.SetSection(a);Signals.SetSynchronized(!1)};
List.DrawCharts=function(){var a;if(List.USE_CANVAS)for(;a=List.ChartsQueue.pop();)Charts.RenderAvatarNew($("chart_"+a.chart_id),a.chart,119,47,a.is_grayed);else for(;a=List.ChartsQueue.pop();)Charts.RenderAvatarOld($("chart_"+a.chart_id),a.chart,119,47)};List.FitCurrentTableHeader=function(){switch(List.CurrentSection){case "all":case "paid":case "free":case "favorites":List.FitTableHeader("signals-header");case "my":List.FitTableHeader("statistics-header")}};
List.FitTableHeader=function(a){if(a=$(a)){window.onresize||(window.onresize=List.FitCurrentTableHeader);a=a.getElementsByTagName("LI");for(var b=0;b<a.length;b++){var c=a[b].firstChild;c&&(c.style.width=a[b].offsetWidth+"px")}}};
List.SetSection=function(a,b){clearTimeout(GlobalCounter);Signals.LoadingBar.Hide();Signals.SetSynchronized(!0);var c=a!=List.CurrentSection;List.FetchPosition=0;List.SignalsParameters.from=0;List.CurrentSection=a;switch(a){case "all":case "paid":case "free":case "favorites":var d=$("signals-list-container");d.onscroll=List.OnScrollSignals;$("statistics-list-container").style.display="none";d.style.display="block";List.SignalsParameters.price=a;var e=Signals.Fetch(List.SignalsParameters);"dataError"in
e&&(e.signals={dataError:e.dataError});List.FillSignals(e.signals,b);break;case "my":d=$("statistics-list-container");$("signals-list-container").style.display="none";d.style.display="block";b=Signals.FetchStatistics(List.StatisticsParameters);"dataError"in b&&(b.subscriptions={dataError:b.dataError});List.FillStatistics(b.subscriptions);break;default:Signals.SetSynchronized(!1);return}b=$("sections").getElementsByTagName("LI");for(e=0;e<b.length;e++)b[e].className=b[e].className.replace("selected",
"");if(a=$("section_"+a))a.className+=" selected";c&&(d.scrollTop=0);Signals.SetSynchronized(!1)};List.SetSorting=function(a,b,c,d,e,f){Signals.SetSynchronized(!0);var g=c,h=1;e?0==a.sort.indexOf(c)?(g=e,c=f,h=2):(g=c,c=d):c="desc"==d?a.sort==c+"_desc"?"asc":"desc":a.sort==c+"_asc"?"desc":"asc";a=$(a.header);a=querySelectorAllFn(a,".signal-сard__col");for(d=0;d<a.length;d++)a[d].firstChild.className="";b.className+=" sort-"+c+"-field"+h;Signals.SetSynchronized(!1);return g+"_"+c};List=List||{};List.OnScrollSignals=function(){var a=$("signals-list");if(!(this.clientHeight+this.scrollTop<a.offsetHeight)&&List.SignalsParameters.price){List.SignalsParameters.from=List.FetchPosition;a=Signals.Fetch(List.SignalsParameters).signals;if(!a||a.length<List.FETCH_PORTION)this.onscroll=null;a&&0<a.length&&List.FillSignals(a)}};
List.FillSignals=function(a,b){if(a){if("dataError"in a){b=$("signals-list");if(!b)return;b.innerHTML='<div class="error-block">'+a.dataError+"</div>";return!1}0==List.FetchPosition&&(List.ChartsQueue=[]);List.FetchPosition+=a.length;List.addSignalsRows(a);List.FitSignalsTableHeader()}};
List.addSignalsRows=function(a,b,c){function d(a){if("object"!=typeof a)return"";var b=""+('<div class="signal-сard" id="'+a.id+'"');b+=' onclick="return Signals.Select(event,'+a.id+',false);"';a.chart_id=a.id;b=b+'><div class="signal-сard__col signal-сard__chart-col"><div class="signal-сard__chart-wrapper"'+(' id="chart_'+a.chart_id+'"');b+=' title="'+Localization.Get("growth")+'"';b+=">";0==a.trade_mode&&a.chart&&(b=b+'<span class="mark-real"'+(' title="'+Localization.Get("real")+'"'),b+="></span>");
b=b+'</div></div><div class="signal-сard__col signal-сard__name-col">'+('<a class="signal-сard__name" href="javascript:void(false);">'+a.name+"</a>");b+='<div class="signal-сard__price">'+Helpers.FormatThousands((a.equity||0).toFixed(1E3<(a.equity||0)?0:2))+" "+(a.currency||"")+"</div>";b=b+'</div><div class="signal-сard__col signal-сard__weeks-col">'+(Helpers.FormatThousands((a.gain||0).toFixed(2))+"% / "+(a.weeks||0));b=b+'</div><div class="signal-сard__col signal-сard__subscribers-col">'+(a.subscribers||
0);a.subscribers_funds&&(b+=" / "+Helpers.FormatMoney(a.subscribers_funds||0)+" USD");b=b+'</div><div class="signal-сard__col signal-сard__trades-col">'+(Helpers.FormatThousands(a.trades||0)+" /"+Math.round(100*(a.win||0))+"%");b+='</div><div class="signal-сard__col signal-сard__maxdd-col">';b=a.max_drawdown&&0!=a.max_drawdown?a.max_drawdown&&30<a.max_drawdown?b+('<em class="red">'+a.max_drawdown.toFixed(1>a.max_drawdown?2:0)+"%</em>"):b+((a.max_drawdown||0).toFixed(1>a.max_drawdown?2:0)+"%"):b+'<em class="gray">N/A</a>';
b+=" / "+(a.profit_factor||0).toFixed(2);b+='</div><div class="signal-сard__col signal-сard__button-col"><a href="javascript:void(false);" class="button button_medium button_100';Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id==a.id?b=b+' " >'+Localization.Get("subscribed"):0<a.price?(b=b+' button_white-bg-green" title="'+Localization.Get("subscribe_for",[window.priceToString(a.price)]),b=b+'" onclick="'+("Signals.Select(event,"+a.id+",true);"),b=b+'" >'+(window.priceToString(a.price)+
" USD")):(b=b+' button_white-green" title="'+Localization.Get("subscribe_free"),b=b+'" onclick="'+("Signals.Select(event,"+a.id+",true);"),b+='" >FREE');b+='</a><span class="icon star';b=-1===window.indexOfArray(List.Favorites,a.id)?b+'" title="'+Localization.GetTooltip("favorites_add"):b+' selected" title="'+Localization.Get("favorites_del");b=b+'"  id="'+("star_"+a.id+'"');b=b+'" onclick="'+("return List.ToggleFavorite(event,"+a.id+");");b+='" ></span></div>';a.chart&&(List.USE_CANVAS?(List.ChartsQueue.push(a),
setTimeout(List.DrawCharts,1)):setTimeout(function(){Charts.RenderAvatarOld($("chart_"+a.chart_id),a.chart,119,47)},2));return b+"</div>"}function e(b){var c="";for(currentSignal in b)b.hasOwnProperty(currentSignal)&&(c+=d(b[currentSignal]));g.insertAdjacentHTML("beforeend",c);f+=10;var h=a.slice(f,f+10);h&&0<h.length&&(GlobalCounter=setTimeout(function(){e(h)},0))}var f=b||0,g=$("signals-list");GlobalCounter=setTimeout(function(){0!=List.SignalsParameters.from||b&&0!=b||(g.innerHTML="");e(a.slice(f,
f+10))},0)};List.FitSignalsTableHeader=function(){return List.FitTableHeader("signals-header")};List.SetSortingSignals=function(a,b,c,d,e){List.SignalsParameters.sort=List.SetSorting(List.SignalsParameters,a,b,c,d,e);List.SetSection(List.CurrentSection)};
List.ToggleFavorite=function(a,b){b=b||Details.Current.id;var c=$("star"),d=$("star_"+b),e=window.indexOfArray(List.Favorites,b);-1==e?(c&&(c.className="icon star selected",c.innerHTML=c.title=Localization.Get("favorites_del")),d&&(d.className+=" selected",d.title=Localization.Get("favorites_del")),List.Favorites.push(b),Signals.FavoritesAdd(b)):(c&&(c.className="icon star",c.innerHTML=c.title=Localization.Get("favorites_add")),d&&(d.className=d.className.replace("selected",""),d.title=Localization.GetTooltip("favorites_add")),
List.Favorites.splice(e,1),Signals.FavoritesDelete(b));if("favorites"==List.CurrentSection)if(Details.Current)List.SetSection(List.CurrentSection,!0);else{if(b=$("row_"+b))b.style.opacity=.5;setTimeout(function(){List.SetSection(List.CurrentSection,!0)},300)}a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0);a&&a.preventDefault&&a.preventDefault();return!1};List=List||{};List.FillStatistics=function(a){if(a){if("dataError"in a){var b=$("statistics-list");if(!b)return;b.innerHTML='<div class="error-block">'+a.dataError+"</div>";return!1}0==List.FetchPosition&&(List.ChartsQueue=[]);List.FetchPosition+=a.length;List.addStatisticsRows(a);List.FitStatisticsTableHeader()}};
List.addStatisticsRows=function(a,b,c){function d(a){if("object"!=typeof a)return"";var b=Signals.CurrentSubscription&&a.signal_id==Signals.CurrentSubscription.signal.id&&a.date_start<=Signals.CurrentSubscription.subscription.date_start&&a.date_expiration>Signals.CurrentSubscription.subscription.date_start;a.is_grayed=!b;a.chart_id=a.signal_id+"_"+a.date_expiration;var c=""+('<div class="signal-сard'+(b?"":" grayed")+'" id="row_sub_'+a.signal_id+'"');c+=' onclick="return Signals.SelectStatistics(event,'+
a.signal_id+","+a.date_start+","+a.date_expiration+',false);"';c=c+'><div class="signal-сard__col signal-сard__chart-col"><div class="signal-сard__chart-wrapper"'+(' id="chart_'+a.chart_id+'"');c+=' title="'+Localization.Get("growth")+'"';c=c+'></div></div><div class="signal-сard__col signal-сard__name-col">'+('<a class="signal-сard__name" href="javascript:void(false);">'+(a.signal_name||a.name)+"</a>");c+='</div><div class="signal-сard__col signal-сard__weeks-col">';c=a.gain&&0>a.gain?c+('<em class="red">'+
Helpers.FormatThousands((100*(a.gain||0)).toFixed(2))+"%</em> / "+(a.weeks||0)):c+(Helpers.FormatThousands((100*(a.gain||0)).toFixed(2))+"% / "+(a.weeks||0));c=c+'</div><div class="signal-сard__col signal-сard__trades-col">'+(Helpers.FormatThousands(a.trades||0)+" / "+Math.round(100*(a.win||0))+"%");c+='</div><div class="signal-сard__col signal-сard__maxdd-col">';c=30<(a.max_dd||0)?c+('<em class="red">'+Math.round(a.max_dd||0)+"%</em>"):c+(Math.round(a.max_dd||0)+"%");c=a.profit_factor||0!=a.profit_factor?
a.profit_factor?c+(" / "+(a.profit_factor||0).toFixed(2)):c+' / <em class="gray">N/A</em>':c+" / 0";c+='</div><div class="signal-сard__col signal-сard__total-cost-col">';if(a.price_total||0==a.price_total)c+=Math.round(a.price_total)+" USD";c+='</div><div class="signal-сard__col signal-сard__expiration-col">';a.date_expiration&&(c+=Helpers.ConvertUnixTime(a.date_expiration,!1));c+='</div><div class="signal-сard__col signal-сard__button-col"><a href="javascript:void(false);" class="button button_medium button_100';
var d="Signals.Select(event,"+a.signal_id+",true);";b?(c+="  button_white-bg-blue ",b=new Date(1E3*Signals.CurrentSubscription.subscription.date_expiration),a.signal_state&Signals.FLAG_NONRENEWABLE?(c=c+' button_disabled" disabled="disabled" title="'+Localization.Get("renew_prohibited"),c=c+'" >'+Localization.Get("renew")):62<Helpers.DaysBetween(new Date,b)?(c=c+' button_disabled" disabled="disabled" title="'+Localization.Get("renew_limit"),c=c+'" >'+Localization.Get("renew")):(c=0<a.signal_price?
c+'" title="'+Localization.Get("renew_for",[a.signal_price.toFixed(2)]):c+'" title="'+Localization.Get("renew_free"),c=c+('" onclick="'+d)+'" >'+Localization.Get("renew"))):(a.signal_state&Signals.FLAG_NONSUBSCRIBABLE?(c+=" button_disabled",c+='" disabled="disabled"',c+=' title="',c+=Localization.Get("subscribe_prohibited"),c+='" >'):Signals.CurrentSubscription?(c+=" button_disabled",c+='" disabled="disabled"',c+=" >"):(0<a.signal_price?(c+=" button_white-bg-green",c+='" title="',c+=Localization.Get("subscribe_for",
[window.priceToString(a.signal_price)])):(c+=" button_white-green",c+='" title="',c+=Localization.Get("subscribe_free")),c=c+('" onclick="'+d)+'" >'),c+=Localization.Get("subscribe"));c+="</a>";c+="</div>";a.chart&&(List.ChartsQueue.push(a),setTimeout(List.DrawCharts,1));return c+="</div>"}function e(b){var c="";for(currentSignal in b)b.hasOwnProperty(currentSignal)&&(c+=d(b[currentSignal]));g.insertAdjacentHTML("beforeend",c);f+=10;var h=a.slice(f,f+10);h&&0<h.length&&(GlobalCounter=setTimeout(function(){e(h)},
0))}var f=b||0||0,g=$("statistics-list");g&&(GlobalCounter=setTimeout(function(){g.innerHTML="";e(a.slice(f,f+10))},0))};List.FitStatisticsTableHeader=function(){return List.FitTableHeader("statistics-header")};List.SetSortingStatistics=function(a,b,c,d,e){List.StatisticsParameters.sort=List.SetSorting(List.StatisticsParameters,a,b,c,d,e);List.SetSection(List.CurrentSection)};var Details;Details||(Details={});Details.Current=null;Details.Existing=null;Details.TabsSynchronized=!1;Details.Platform=4;
Details.Init=function(a){Details.Platform=a;switch(a){case 5:var b=$("signal_trading_header_mt4");b&&b.parentNode&&b.parentNode.removeChild(b);break;default:(b=$("signal_trading_header_mt5"))&&b.parentNode&&b.parentNode.removeChild(b)}if(b=$("signal_howto"))b.href="#",b.onclick=function(b){external.OpenUrl("https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+"/articles/523?utm_campaign=MetaTrader+"+a+"+Terminal&utm_medium=special&utm_source=How+to+subscribe+signals");b=b||window.event;b.preventDefault?
b.preventDefault():b.returnValue=!1};var c=Localization.Get("signal_youtube_url").replace("{MT}",a).replace("{MT}",a);if(b=$("signal_toolbar_youtube"))b.href="#",b.onclick=function(a){external.OpenUrl(c.replace("{SRC}","signals+actions"));a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=!1};if(b=$("list_toolbar_youtube"))b.href="#",b.onclick=function(a){external.OpenUrl(c.replace("{SRC}","signals+list"));a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=!1};$("signal_youtube").innerHTML=
Localization.Get("signal_youtube").replace("<a>","<a onclick=\"external.OpenUrl('"+c.replace("{SRC}","signals+stats")+'\');" href="javascript:void(false);">')};
Details.FillSidebarButtons=function(a){var b=document.getElementById("buttonsSidebar");if(!b)return!1;b.innerHTML="";if(!(a&&"id"in a))return!1;var c="";if(Signals.CurrentSubscription&&"signal"in Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id==a.id)Signals.CurrentSubscription.subscription&&(c=62<Helpers.DaysBetween(new Date,new Date(1E3*Signals.CurrentSubscription.subscription.date_expiration))?c+('<a disabled="disabled" class="button button_blue button_disabled" href="javascript:void(false);">'+
Localization.Get("renew_limit")+"</a>"):c+('<a class="button button_blue" href="javascript:void(false);" onclick="Details.TogglePayments(true,true,false)">'+(0<a.price?Localization.Get("renew_for_short",[window.priceToString(a.price)]):Localization.Get("renew_free"))+"</a>")),c+='<a class="button button_red" href="javascript:void(false);" onclick="Details.TogglePayments(true,false,true)">'+Localization.Get("unsubscribe")+"</a>";else{var d=Localization.Get("subscribe_free"),e=!0;if(a&&"price"in a&&
0<a.price&&(e=!1,d=Localization.Get("subscribe_for",[window.priceToString(a.price)]),Signals.ShowDailyPrice)){var f=a.price/30;f=window.priceToString(f);f=parseFloat(f)+" USD";var g=Localization.Get("per_day");g=g.replace("{0}",f);d+="<br>"+g}c=0!=a.state||0==Signals.CurrentAccount.trade_mode&&0!=a.trade_mode||a.subscription_allowance?c+('<a class="button button_disabled" href="javascript:void(false);" disabled="disabled">'+Localization.Get("subscribe")+"</a>"):Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id!=
a.id?c+('<a class="button button_disabled" href="javascript:void(false);" disabled="disabled">'+d+"</a>"):c+('<a class="button'+(e?" button_blue":"")+(Signals.ShowDailyPrice?" button_multiline":"")+'" href="javascript:void(false);" onclick="Details.TogglePayments(true,false,false)">'+d+"</a>")}b.innerHTML=c};
Details.Show=function(a){var b=$("signal_popup");if(b){if("dataError"in a){var c=$("signal_warnings");if(c){c.innerHTML='<div class="error-block">'+a.dataError+"</div>";b.style.visibility="visible";(a=$("signal_details_statistics"))&&removeClass(a,"hidden");a=$("signal_subscribe");b=$("signal_renew");c=$("signal_unsubscribe");var d=$("unsubscribe_first"),e=$("paid_signal_notes");a&&b&&c&&d&&e&&(a.style.display="none",b.style.display="none",c.style.display="none",d.style.display="none",e.style.display=
"none")}return!1}Details.Current=a;Details.Existing=a;Signals.SetSynchronized(!0);b.style.height=document.documentElement.clientHeight+"px";Details.UpdateTopButtons();1E3<document.documentElement.clientWidth?$("top_bar_view").className="top_bar":$("top_bar_view").className="top_bar shrinked";c=$("star");a.local?(-1===window.indexOfArray(List.Favorites,a.id)?(c.className="icon star",c.innerHTML=Localization.Get("favorites_add"),c.title=Localization.GetTooltip("favorites_add")):(c.className="icon star selected",
c.innerHTML=c.title=Localization.Get("favorites_del")),c.parentNode.disabled="",c.parentNode.onclick=List.ToggleFavorite):(c.className="icon star disabled",c.innerHTML=Localization.Get("favorites_add"),c.title=Localization.GetTooltip("favorites_add"),c.parentNode.disabled="disabled",c.parentNode.onclick="");c=$("signal_missing_stub");d=$("visualize");2==a.state?($("signal_title").innerHTML=a.name,removeClass(c,"hidden"),d.className="icon visualize disabled",d.parentNode.disabled="disabled",d.parentNode.onclick=
""):(c.className+=" hidden",d.className="icon visualize",d.parentNode.disabled="",d.parentNode.onclick=function(){Signals.Visualize()},Details.FillStatistics(a),Details.FillSidebarButtons(a),Details.BuildDistribution(a,"signal_distribution"),Details.FillWarnings(a),Details.InitTabs("signal_tabs_top",Details.SelectTab));Details.ShowAsIs(b);Signals.SetSynchronized(!1)}};
Details.RenderWarnings=function(a){if(!a.subscription_allowance)return"";for(var b="leverage drawdown growth notseller banned blocked".split(" "),c="",d=0,e=1;d<b.length;d++,e<<=1)0!=(a.subscription_allowance&e)&&(c+="<p>",c+='<span class="icon attention"></span>',c+=Localization.Get("subscribe_disabled_"+b[d]),c+="</p>");return c};
Details.FillWarnings=function(a){var b=$("signal_warnings");if(b){for(;0<b.childNodes.length;)b.removeChild(b.childNodes[0]);b.insertAdjacentHTML("beforeend",Details.RenderWarnings(a));b.style.display="block"}};
Details.UpdateTopButtons=function(){var a=Details.Existing;var b=$("signal_subscribe");var c=$("signal_renew"),d=$("signal_unsubscribe"),e=$("unsubscribe_first"),f=$("paid_signal_notes");if(!(a&&"id"in a))return!1;if(Signals.CurrentSubscription&&"signal"in Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id==a.id){c.innerHTML=0<a.price?Localization.Get("renew_for",[window.priceToString(a.price)]):Localization.Get("renew_free");b.style.display="none";e.style.display="none";c.style.display=
"inline-block";d.style.display="inline-block";f.style.display="none";$("tab_subscription").style.display="inline-block";Signals.CurrentSubscription.subscription&&(62<Helpers.DaysBetween(new Date,new Date(1E3*Signals.CurrentSubscription.subscription.date_expiration))?(c.disabled="disabled",c.className="button button_little button_blue button_disabled",c.innerHTML=Localization.Get("renew_limit")):(c.disabled="",c.className="button button_little button_blue"));if(b=$("signal_review_add"))b.style.display=
"block",b.setAttribute("href","https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+"/signals/"+a.id+"?#!tab=reviews");$("signal_howto").style.display="none";$("signal_toolbar_youtube").style.display="none"}else{var g=!0;a&&"price"in a&&(0<a.price?(g=!1,b.innerHTML=Localization.Get("subscribe_for",[window.priceToString(a.price)])):(g=!0,b.innerHTML=Localization.Get("subscribe_free")));b.style.display="inline-block";c.style.display="none";d.style.display="none";$("tab_subscription").style.display=
"none";f.style.display=0<a.price?"block":"none";0!=a.state||0==Signals.CurrentAccount.trade_mode&&0!=a.trade_mode||a.subscription_allowance?(b.className="button button_little button_disabled",b.disabled="disabled",e.style.display="none",b.innerHTML=Localization.Get("subscribe"),$("signal_howto").style.display="none",$("signal_toolbar_youtube").style.display="none"):Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id!=a.id?(b.className="button button_little button_disabled",b.disabled=
"disabled",e.style.display="inline-block",a=$("unsubscribe_first_link"),a.setAttribute("onclick","Signals.Select(event,"+Signals.CurrentSubscription.signal.id+",false);"),a.innerHTML=Signals.CurrentSubscription.signal.name,$("signal_howto").style.display="none",$("signal_toolbar_youtube").style.display="none"):(b.className="button button_little"+(g?" button_blue":""),b.disabled="",e.style.display="none",$("signal_howto").style.display="inline-block",$("signal_toolbar_youtube").style.display="inline-block");
if(b=$("signal_review_add"))b.style.display="none"}};Details.Reset=function(){Details.Existing=null;Details.Current=null};
Details.ShowAsIs=function(a){if(!a&&(a=$("signal_popup"),!a))return;Details.Current||(Details.Current=Details.Existing);Details.Current&&(Details.SelectTab(null,$("tab_growth")),Statistics.Hide(),document.documentElement.style.overflow="hidden",a.style.visibility="visible",$("signal_main_content").scrollTop=0,Signals.PaymentsMessageMode&&Signals.PaymentCompleteResult?Signals.PaymentSystem.PaymentComplete(Signals.PaymentCompleteResult.success,Signals.PaymentCompleteResult.result):Details.TogglePayments(Signals.SubscribeMode||
Signals.UnsubscribeMode,null,Signals.UnsubscribeMode),Signals.SubscribeMode=!1,Signals.UnsubscribeMode=!1,Signals.PaymentsMessageMode=!1,Signals.PaymentCompleteResult=!1)};Details.SwitchToStatistics=function(){Details.Current&&(Signals.InitSubscription(),Signals.CurrentSubscription&&Signals.SelectStatistics(null,Signals.CurrentSubscription.signal.id,Signals.CurrentSubscription.subscription.date_start,Signals.CurrentSubscription.subscription.date_expiration))};
Details.Hide=function(){var a=$("signal_popup");a&&(Details.Current=null,a.style.visibility="hidden",document.documentElement.style.overflow="auto")};
Details.TogglePayments=function(a,b,c){var d=$("paymentSystemListBlock"),e=$("signal_details_payment");if(d){try{external.PurchaseCancel()}catch(f){errorsConsole.Add(f)}d.parentNode.removeChild(d);Helpers.Class(e,"hidden")}a?((a=external.GetLogin())&&0!==a.length||external.GetOptions(),Statistics.Hide(),Details.ViewPaymentDiv(b,c)):(removeClass($("signal_details_statistics"),"hidden"),Helpers.Class(e,"hidden"),$("signal_popup_close").setAttribute("href","javascript:Details.Hide()"))};
Details.ViewPaymentDiv=function(a,b){if(Details.Current){null!=a||b||(a=Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id==Details.Current.id);$("signal_details_statistics").className+=" hidden";$("signal_popup_close").setAttribute("href","javascript:Details.TogglePayments(false)");var c=$("signal_details_payment");removeClass(c,"hidden");b?Signals.PaymentSystem.RenderViewConfirmUnsibscibe(c,Details.Current):Details.Current&&0<Details.Current.price&&Details.Current.author_login!=
user_login?Signals.PaymentSystem.RenderPaymentSystem(c,Details.Current,"2",a?"renew":"subscribe"):Signals.PaymentSystem.SubscribeNow(Details.Current.id,a?"renew":"subscribe")}};Details.InitTabs=function(a,b){a=$(a);a.className=a.className.replace(" vari_weight","");for(var c=a.getElementsByTagName("li"),d=0;d<c.length;d++)c[d].style.width="auto",0<c[d].clientWidth&&(c[d].style.width=c[d].clientWidth-15+"px"),b&&(c[d].onclick=b);a.className+=" vari_weight"};
Details.SelectTab=function(a,b){if(!Details.TabsSynchronized&&(b=b||this,!(0<=b.className.indexOf("selected"))&&(a=b.parentNode))){Details.TabsSynchronized=!0;for(var c=a.getElementsByTagName("LI"),d=0;d<c.length;d++)c[d]!=b&&-1!=c[d].className.indexOf("selected")&&(c[d].className=c[d].className.replace("selected",""),a=$("tab_content_"+c[d].id.substring(4)))&&(a.className=a.className.replace("selected",""));b.className+=" selected";b=b.id.substring(4);if(a=$("tab_content_"+b))a.className+=" selected";
switch(b){case "growth":$("signal_tabs_bottom_container").style.display="block";$("trade_data_columns").style.display="block";break;case "balance":case "equity":$("signal_tabs_bottom_container").style.display="none";$("trade_data_columns").style.display="block";break;case "risks":case "distr":case "descr":case "reviews":case "news":$("signal_tabs_bottom_container").style.display="none",$("trade_data_columns").style.display="none"}Details.TabsSynchronized=!1}};
Details.GetChartWidth=function(){var a=document.documentElement.clientWidth-310;return a&&200<a?a:200};Details.GetChartHeight=function(){var a=.7*document.documentElement.clientHeight;return a&&200<a?a:200};Details||(Details={});
Details.BuildDistribution=function(a,b){var c=$(b+"_chart");if(c&&a.symbols&&0!==a.symbols.length){c.style.display="table";c=a.symbols[0];var d=Helpers.RoundScaleMax(c.buy+c.sell);c=d.step;d=d.max;var e=$(b+"_chart_data");e=Helpers.ClearTableBody(e);for(var f=0;f<a.symbols.length;f++){var g=a.symbols[f];var h=document.createElement("TR");var l=document.createElement("TD");l.style.width="60px";l.innerHTML=g.name;h.appendChild(l);l=document.createElement("TD");l.style.width="30px";l.style.textAlign=
"right";l.innerHTML=g.buy+g.sell;h.appendChild(l);l=document.createElement("TD");l.className="bar";l.title=g.name+": "+(g.buy+g.sell);l.style.width="30%";b=document.createElement("DIV");b.style.width=100*Math.max(.01,(g.buy+g.sell)/d)+"%";l.appendChild(b);h.appendChild(l);l=document.createElement("TD");l.className="bar";l.title=g.name+": "+g.sell;l.style.width="30%";b=document.createElement("DIV");b.className="d";b.style.cssFloat="right";b.style.width=100*Math.max(.01,g.sell/d)+"%";l.appendChild(b);
h.appendChild(l);l=document.createElement("TD");l.className="bar";l.title=g.name+": "+g.buy;l.style.width="30%";b=document.createElement("DIV");b.className="u";b.style.cssFloat="left";b.style.width=100*Math.max(.01,g.buy/d)+"%";l.appendChild(b);h.appendChild(l);e.appendChild(h)}h=document.createElement("TR");h.className="nohl";h.appendChild(document.createElement("TD"));h.appendChild(document.createElement("TD"));l=document.createElement("TD");l.className="scale";b=document.createElement("DIV");b.className=
"left";for(f=c;f<=d;f+=c)a=document.createElement("I"),a.style.right=100-100*f/d+"%",a.innerHTML=f,b.appendChild(a);l.appendChild(b);h.appendChild(l);l=document.createElement("TD");l.className="scale";b=document.createElement("DIV");b.className="right";for(f=c;f<=d;f+=c)a=document.createElement("I"),a.style.left=100-100*f/d+"%",a.innerHTML=f,b.appendChild(a);l.appendChild(b);h.appendChild(l);l=document.createElement("TD");l.className="scale";b=document.createElement("DIV");b.className="left";for(f=
c;f<=d;f+=c)a=document.createElement("I"),a.style.right=100-100*f/d+"%",a.innerHTML=f,b.appendChild(a);l.appendChild(b);h.appendChild(l);e.appendChild(h)}else c.style.display="none"};Details||(Details={});
Details.FillStatistics=function(a){Details.FillDetailsPlain(a,Details.FieldsTable);for(var b in Details.ValueTable)Details.FillDetailsStatistics(a,Details.ValueTable[b],b);$("signal_time_from_latest_trade").innerHTML=Helpers.FormatTimeElapsed(60*a.minutes_from_latest_trade);$("signal_max_dd_total").title=Localization.Get("maxdd_value",[a.max_dd,a.currency]);$("signal_trade_mode").innerHTML=Constants.TradeMode[a.trade_mode];if(b=$("signal_author"))b.href="#",b.onclick=function(b){external.OpenUrl("https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+
"/users/"+a.author_login);b=b||window.event;b.preventDefault?b.preventDefault():b.returnValue=!1};if(b=$("signal_details"))b.href="#",b.onclick=function(b){external.OpenUrl("https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+"/signals/"+a.id+"?utm_campaign=MetaTrader+"+platform+"+Terminal&utm_medium=special&utm_source=Signal+details+in+community");b=b||window.event;b.preventDefault?b.preventDefault():b.returnValue=!1};if(b=$("signal_history_tab"))b.href="#",b.onclick=function(b){external.OpenUrl("https://www.mql5.com/"+
Localization.GetDefaultLanguageMql5()+"/signals/"+a.id+"#!tab=history");b=b||window.event;b.preventDefault?b.preventDefault():b.returnValue=!1};$("signal_equity")&&(a.equity>a.balance?$("signal_equity").className="blue":a.equity<a.balance&&($("signal_equity").className="red"));(b=$("signal_expected_slippage"))&&b.parentNode&&((a.expected_slippage||0==a.expected_slippage)&&Signals.CurrentAccount?(b.innerHTML=a.expected_slippage.toFixed(2),b.parentNode.title=Localization.Get("slippage_tooltip",[a.expected_slippage.toFixed(4),
Constants.TradeMode[Signals.CurrentAccount.trade_mode],a.broker,Signals.CurrentAccount.broker])):(b.innerHTML=Localization.Get("slippage_na"),b.parentNode.title=Signals.CurrentAccount?Localization.Get("slippage_na_tooltip",[a.broker,Signals.CurrentAccount.broker]):""));Details.FillChart(a,"growth");Details.FillChart(a,"balance");Details.FillChart(a,"equity");Details.RenderEquityBalancesMap(a);Details.FillTradingTable(a);Details.FillReviews(a);Details.FillNews(a)};
Details.FieldsTable={signal_title:"name",signal_author:{_:"author_name",title:"author_login"},signal_broker:"broker",signal_description:"description"};
Details.ValueTable={plain:{signal_weeks:"weeks",signal_subscribers:"subscriptions_total",signal_trades_a_week:"deals_per_week",signal_leverage:"leverage",signal_reviews_total:"reviews_total",signal_news_total:"news_total",signal_trades:"trades",signal_profit_trades:"profit_trades",signal_loss_trades:"loss_trades",signal_con_profit_max_trades:"con_profit_max_trades",signal_max_con_profit_trades:"max_con_profit_trades",signal_sharpe_ratio:"sharpe_ratio",signal_recovery_factor:"recovery_factor",signal_long_trades:"long_trades",
signal_short_trades:"short_trades",signal_profit_factor:"profit_factor",signal_con_loss_max_trades:"con_loss_max_trades",signal_max_con_loss_trades:"max_con_loss_trades",signal_con_profit_max_trades_risk:"con_profit_max_trades",signal_max_con_profit_trades_risk:"max_con_profit_trades",signal_con_loss_max_trades_risk:"con_loss_max_trades",signal_max_con_loss_trades_risk:"max_con_loss_trades"},currency:{signal_equity:"equity",signal_initial_deposit:"initial_deposit",signal_deposits:"deposit",signal_withdrawals:"withdrawals",
signal_balance:"balance"},currency_colored:{signal_profit:"profit",signal_max_profit:"max_profit",signal_min_profit:"min_profit",signal_gross_profit:"gross_profit",signal_gross_loss:"gross_loss",signal_con_profit_max:"con_profit_max",signal_max_con_profit:"max_con_profit",signal_expected_payoff:"expected_payoff",signal_avg_profit:"avg_profit",signal_avg_loss:"avg_loss",signal_con_loss_max:"con_loss_max",signal_max_con_loss:"max_con_loss",signal_con_profit_max_risk:"con_profit_max",signal_max_con_profit_risk:"max_con_profit",
signal_con_loss_max_risk:"con_loss_max",signal_max_con_loss_risk:"max_con_loss",signal_max_profit_risk:"max_profit",signal_min_profit_risk:"min_profit"},currency_colored_dd:{signal_abs_drawdown:"abs_drawdown",signal_max_drawdown:"max_drawdown",signal_rel_drawdown:"rel_drawdown",signal_equity_drawdown:"equity_drawdown"},percents:{},percents_colored:{signal_gain:"gain",signal_gain2:"gain",signal_monthly_growth:"monthly_growth",signal_annual_forecast:"annual_forecast"},percents_colored_dd:{signal_max_dd_total:"max_dd_percent",
signal_max_drawdown_percents:"max_drawdown_percent",signal_rel_drawdown_percents:"rel_drawdown_percent",signal_equity_drawdown_percents:"equity_drawdown_percent"},time:{signal_avg_holding_time:"avg_holding_time"},money:{signal_funds:"subscribers_funds"}};
Details.FillTradingTable=function(a){var b=$("signal_trading");if(b){b=Helpers.ClearTableBody(b);var c=2,d=!0;if(a.positions&&0!==a.positions.length||a.orders&&0!==a.orders.length||0!=a.pending_profit){if(a.positions&&0<a.positions.length){c=a.positions[0].digits_currency||2;for(var e=0;e<a.positions.length;e++){var f=a.positions[e];d=!d;c=f.digits_currency||2;switch(Details.Platform){case 5:var g=[f.symbol,a.limited?"":Helpers.ConvertUnixTime(f.time_update,!0),a.limited?"":Constants.TradeAction[f.action],
a.limited?"":Helpers.FormatThousands(f.volume.toFixed(2)),Helpers.FormatThousands(f.price_open.toFixed(f.digits)),Helpers.FormatThousands(f.sl.toFixed(f.digits)),Helpers.FormatThousands(f.tp.toFixed(f.digits)),Helpers.FormatThousands(f.price_close.toFixed(f.digits))];var h=0;break;default:g=[a.limited?"":Helpers.ConvertUnixTime(f.time_open,!a.limited),a.limited?"":Constants.TradeAction[f.type],a.limited?"":Helpers.FormatThousands(f.volume.toFixed(2)),f.symbol,Helpers.FormatThousands(f.price_open.toFixed(f.digits)),
Helpers.FormatThousands(f.sl.toFixed(f.digits)),Helpers.FormatThousands(f.tp.toFixed(f.digits)),Helpers.FormatThousands(f.price_close.toFixed(f.digits))],h=-1}Details.AddTableDataRow(b,g,[Helpers.FormatThousands(f.comission.toFixed(c)),Helpers.FormatThousands(f.storage.toFixed(c)),Helpers.FormatThousands(f.profit.toFixed(2))],0,d,h)}}Details.AddTableDataRow(b,[],[Helpers.FormatThousands(a.pending_comission.toFixed(c)),Helpers.FormatThousands(a.pending_storage.toFixed(c)),Helpers.FormatThousands(a.pending_profit.toFixed(2))],
8);if(a.orders&&0<a.orders.length)for(d=!0,e=0;e<a.orders.length;e++){f=a.orders[e];d=!d;switch(Details.Platform){case 5:g=[f.symbol,a.limited?"":Helpers.ConvertUnixTime(f.time_update,!0),a.limited?"":Constants.OrderType[f.action],a.limited?"":Helpers.FormatThousands(f.volume.toFixed(2)),Helpers.FormatThousands(f.price_open.toFixed(f.digits)),Helpers.FormatThousands(f.sl.toFixed(f.digits)),Helpers.FormatThousands(f.tp.toFixed(f.digits)),Helpers.FormatThousands(f.price_close.toFixed(f.digits))];h=
0;break;default:g=[a.limited?"":Helpers.ConvertUnixTime(f.time_open,!0),a.limited?"":Constants.OrderType[f.type],a.limited?"":Helpers.FormatThousands(f.volume.toFixed(2)),f.symbol,Helpers.FormatThousands(f.price_open.toFixed(f.digits)),Helpers.FormatThousands(f.sl.toFixed(f.digits)),Helpers.FormatThousands(f.tp.toFixed(f.digits)),Helpers.FormatThousands(f.price_close.toFixed(f.digits))],h=-1}Details.AddTableDataRow(b,g,["","",""],0,d,h,h)}}else Details.AddTableMessageRow(b,Localization.Get("no_positions_orders"),
11)}};Details.AddTableMessageRow=function(a,b,c){var d=document.createElement("TD");d.colSpan=c;d.style.textAlign="center";d.innerHTML=b;b=document.createElement("TR");b.appendChild(d);a.appendChild(b)};
Details.AddTableDataRow=function(a,b,c,d,e,f){var g=document.createElement("TR");d?(e=document.createElement("TD"),e.colSpan=d,g.appendChild(e),g.className="summary"):e&&(g.className="bg");for(d=0;d<b.length;d++)e=document.createElement("TD"),d==f&&(e.style.textAlign="left"),0!=b[d]&&(e.innerHTML=b[d]),g.appendChild(e);for(d=0;d<c.length;d++){e=document.createElement("TD");if(0!=c[d]||d+1==c.length)0==c[d].toString().indexOf("-")?e.className="red":0!=c[d].toString().indexOf("0")&&(e.className="blue"),
e.innerHTML=c[d];g.appendChild(e)}a.appendChild(g)};Details.FillChart=function(a,b){var c=$("signal_"+b+"_chart");if(c&&c.parentNode){var d=document.createElement("IMG");d.id=c.id;d.setAttribute("src",a[b+"_path"]+"?"+Helpers.NextInt());try{c.getAttribute("usemap")&&d.setAttribute("usemap",c.getAttribute("usemap"))}catch(e){}c.parentNode.replaceChild(d,c)}};
Details.RenderEquityBalancesMap=function(a){var b=$("signal_equity_map");if(b&&a.time_balance_profits_positions&&0!==a.time_balance_profits_positions.length)if(a.time_balance_profits_positions&&0!==a.time_balance_profits_positions.length){var c=document.createElement("MAP");c.name=b.name;c.id=b.id;try{for(var d=0;d<a.time_balance_profits_positions.length;d++){var e=a.time_balance_profits_positions[d];if(!(0>e.x)){var f=a.time_balance_profits[d]+" "+a.currency+", "+Helpers.ConvertUnixTime(a.time_balance_x[d],
!0),g=document.createElement("AREA");g.setAttribute("shape","rect");g.setAttribute("coords",[e.x-10,Math.max(0,e.y-10),e.x+10,e.y+10].join());g.setAttribute("alt",f);g.setAttribute("title",f);c.appendChild(g)}}}catch(h){}b.parentNode.replaceChild(c,b)}else b.innerHTML=""};Details||(Details={});
Details.FillReviews=function(a){$("signal_rating_value").className="rating v"+5*Math.round(2*(a.rating||0));var b=$("signal_reviews");if(b){var c=$("signal_reviews_more"),d=$("signal_reviews_nodata");if(a.reviews&&0!==a.reviews.length){var e=document.createElement("DIV");e.id=b.id;for(var f=Details.BuildReviews(a.reviews),g=0;g<f.length;g++)e.appendChild(f[g]);b.parentNode.replaceChild(e,b);c&&(a.reviews_total>a.reviews.length?(c.style.display="inline-block",c.className="button cmd",c.disabled="",
c.innerHTML=Localization.Get("reviews_more",[a.reviews_total-a.reviews.length])):c.style.display="none");d&&(d.style.display="none")}else b.innerHTML="",c&&(c.style.display="none"),d&&(d.style.display="block")}};
Details.FillNews=function(a){var b=$("signal_news");if(b){var c=$("tab_news");if(a.news&&0!==a.news.length){var d=document.createElement("DIV");d.id=b.id;for(var e=Details.BuildNews(a.news),f=0;f<e.length;f++)d.appendChild(e[f]);b.parentNode.replaceChild(d,b);if(b=$("signal_news_more"))a.news_total>a.news.length?(b.style.display="inline-block",b.className="button cmd",b.disabled="",b.innerHTML=Localization.Get("news_more",[a.news_total-a.news.length])):b.style.display="none";c&&(c.style.display="inline-block")}else c&&
(c.style.display="none")}};
Details.MoreNewsReviews=function(a){var b;if(Details.Current&&(!a||a==Details.Current.id)){var c=Details.Current;var d=Math.max(c.reviews.length,c.news.length);if(a=$("signal_reviews_more"))a.className="button disabled",a.disabled="disabled";var e=$("signal_news_more");e&&(e.className="button disabled",e.disabled="disabled");var f;if((b=external.GetSignalNewsReviews(c.id,d))&&(f=jsonParse(b,8))){if(f.reviews&&0<f.reviews.length)for(c=$("signal_reviews"),b=Details.BuildReviews(f.reviews),d=0;d<b.length;d++)c.appendChild(b[d]);
if(f.news&&0<f.news.length)for(c=$("signal_news"),b=Details.BuildNews(f.news),d=0;d<b.length;d++)c.appendChild(b[d]);a&&(a.style.display="none");e&&(e.style.display="none")}else a&&c.reviews&&c.reviews.length<c.reviews_total&&(a.style.display="inline-block",a.className="button cmd",a.disabled=""),e&&c.news&&c.news.length<c.news_total&&(e.style.display="inline-block",e.className="button cmd",e.disabled="")}};
Details.BuildReviews=function(a){for(var b=[],c=[],d=0;d<a.length;d++){var e=Helpers.GetHashIdByUrl(a[d].avatar_url),f=document.createElement("DIV");f.className="review";var g=document.createElement("DIV");g.className="avatar";var h=document.createElement("IMG");h.className=e;g.appendChild(h);f.appendChild(g);g=document.createElement("DIV");g.className="body";h=document.createElement("SPAN");h.className="author";h.innerHTML=Helpers.UserLinkFull(a[d].author_login,a[d].author_full_name);h.setAttribute("title",
a[d].author_full_name+" ("+a[d].author_login+")");g.appendChild(h);h=document.createElement("SPAN");h.className="date";h.innerHTML=Helpers.ConvertUnixTime(a[d].date_created,!0);g.appendChild(h);h=document.createElement("DIV");h.className="rating rating_small rating_v"+10*a[d].rating.toFixed(1);h.appendChild(document.createElement("DIV"));g.appendChild(h);h=document.createElement("SPAN");h.className="text";h.innerHTML="<p>"+a[d].text.split("\n").join("</p><p>")+"</p>";g.appendChild(h);f.appendChild(g);
b.push(f);c.push({src:a[d].avatar_url,imageName:e})}0<c.length&&setTimeout(function(){window.setImgesAvatarSrcAsync(c);c=[]},10);return b};
Details.BuildNews=function(a){a.reverse();for(var b=[],c=0;c<a.length;c++){var d=document.createElement("DIV");d.className="news-item";var e=document.createElement("DIV");e.className="body";var f=document.createElement("SPAN");f.className="date";f.innerHTML=Helpers.ConvertUnixTime(a[c].date_created,!0);e.appendChild(f);f=document.createElement("SPAN");f.className="text";f.innerHTML="<p>"+a[c].text.split("\n").join("</p><p>")+"</p>";e.appendChild(f);d.appendChild(e);b.push(d)}return b};var Statistics=Statistics||{};Statistics.Current=null;Statistics.TabsSynchronized=!1;
Statistics.Show=function(a){Statistics.Current=a;var b=$("statistics_popup");if(b){b.style.height=document.documentElement.clientHeight+"px";var c=$("statistics_subscribe"),d=$("statistics_renew"),e=$("statistics_unsubscribe"),f=$("subscribed"),g=$("statistics_unsubscribe_first"),h=$("statistics_intro");if(h){if("dataError"in a)return h.innerHTML='<div class="error-block">'+a.dataError+"</div>",document.documentElement.style.overflow="hidden",b.style.visibility="visible",c.style.display="none",g.style.display=
"none",d.style.display="none",e.style.display="none",!1;h.innerHTML=Localization.Get("statistics_intro",[a.signal_name,Helpers.ConvertUnixTime(a.date_start),Helpers.ConvertUnixTime(a.date_expiration)])}Signals.CurrentSubscription&&Signals.CurrentSubscription.signal.id==a.signal_id&&a.date_start<=Signals.CurrentSubscription.subscription.date_start&&a.date_expiration>Signals.CurrentSubscription.subscription.date_start?(d.innerHTML=0<a.signal_price?Localization.Get("renew_for",[a.signal_price.toFixed(2)]):
Localization.Get("renew_free"),c.style.display="none",g.style.display="none",d.style.display="inline-block",e.style.display="inline-block",Signals.CurrentSubscription.subscription&&(f.innerHTML=Localization.Get("subscribed_period",[Helpers.ConvertUnixTime(Signals.CurrentSubscription.subscription.date_start,!0),Helpers.ConvertUnixTime(Signals.CurrentSubscription.subscription.date_expiration,!0)]),f.style.display="inline-block",62<Helpers.DaysBetween(new Date,new Date(1E3*Signals.CurrentSubscription.subscription.date_expiration))?
(d.disabled=!0,d.className="button button_little button_blue button_disabled",d.innerHTML=Localization.Get("renew_limit")):(d.disabled=!1,d.className="button button_little button_blue"))):(c.innerHTML=0<a.signal_price?Localization.Get("subscribe_for",[a.signal_price.toFixed(2)]):Localization.Get("subscribe_free"),c.style.display="inline-block",d.style.display="none",e.style.display="none",f.style.display="none",0<a.signal_state?(c.className="button button_little button_disabled",c.disabled=!0):Signals.CurrentSubscription&&
Signals.CurrentSubscription.signal.id!=a.signal_id?(c.className="button button_little button_disabled",c.disabled=!0,g.style.display="inline-block",c=$("statistics_unsubscribe_first_link"),c.setAttribute("onclick","Signals.SelectStatistics(event,"+Signals.CurrentSubscription.signal.id+","+Signals.CurrentSubscription.subscription.date_start+","+Signals.CurrentSubscription.subscription.date_expiration+");"),c.innerHTML=Signals.CurrentSubscription.signal.name):(c.className=c.className.replace(" disabled",
""),c.disabled=!1,g.style.display="none"));Details.Current&&Details.Hide();document.documentElement.style.overflow="hidden";b.style.visibility="visible";Statistics.FillStatistics(a);Statistics.RenderGrowthTable(a);Details.BuildDistribution(a,"statistics_distribution");$("statistics_main_content").scrollTop=0;Signals.SetSynchronized(!1);Signals.Preload(a.signal_id)}};
Statistics.SwitchToDetails=function(a,b){if(Statistics.Current){var c=Statistics.Current.signal_id;Statistics.Current=null;Signals.Select(null,c,a,b)}};Statistics.Hide=function(){var a=$("statistics_popup");a&&(Statistics.Current=null,a.style.visibility="hidden",document.documentElement.style.overflow="auto")};
Statistics.FillStatistics=function(a){Statistics.FillChart(a,"growth");Details.FillDetailsPlain(a,Statistics.FieldsTable);for(var b in Statistics.ValueTable)Details.FillDetailsStatistics(a,Statistics.ValueTable[b],b)};
Statistics.FillChart=function(a,b){var c=$("statistics_"+b+"_chart");if(c&&c.parentNode){var d=document.createElement("IMG");d.id=c.id;d.setAttribute("src",a[b+"_path"]+"?"+Helpers.NextInt());try{c.getAttribute("usemap")&&d.setAttribute("usemap",c.getAttribute("usemap"))}catch(e){}c.parentNode.replaceChild(d,c)}};Statistics.FieldsTable={statistics_title:"signal_name"};
Statistics.ValueTable={plain:{statistics_trades:"trades",statistics_profit_trades:"profit_trades",statistics_loss_trades:"loss_trades",statistics_profit_factor:"profit_factor"},currency:{},currency_colored:{statistics_max_profit:"max_profit",statistics_min_profit:"min_profit",statistics_gross_profit:"gross_profit",statistics_gross_loss:"gross_loss",statistics_avg_profit:"avg_profit",statistics_avg_loss:"avg_loss"},currency_colored_dd:{statistics_abs_drawdown:"abs_drawdown",statistics_max_drawdown:"max_drawdown",
statistics_rel_drawdown:"rel_drawdown"},percents:{},percents_colored:{},percents_colored_dd:{statistics_max_drawdown_percents:"max_drawdown_percent",statistics_rel_drawdown_percents:"rel_drawdown_percent"},percents_colored_raw:{statistics_monthly_growth:"monthly_growth",statistics_annual_forecast:"annual_forecast"},time:{},money:{}};Statistics.GetChartWidth=function(){var a=document.documentElement.clientWidth-65;return a&&200<a?a:200};
Statistics.GetChartHeight=function(){var a=.7*document.documentElement.clientHeight;return a&&200<a?a:200};
Statistics.RenderGrowthTable=function(a){var b=$("statistics_growth_rows");b.innerHTML="";var c=$("subscription_growth_total");0<a.gain?c.className="blue":0>a.gain&&(c.className="red");c.innerHTML=(100*a.gain).toFixed(10<a.gain?0:2)+"%";if(a.growth_index&&0!==a.growth_index.length){for(var d=c=0,e,f,g=[],h=[],l=0;l<a.growth_index.length;l++)a.growth_index[l].month?g.push(a.growth_index[l]):h.push(a.growth_index[l]);a=g[0];l=g[g.length-1];for(var m=a.year;m<=l.year;m++){var n=document.createElement("DIV");
n.className="row";b.appendChild(n);var k=document.createElement("DIV");k.className="cell year";k.innerHTML=m;n.appendChild(k);var p=m==a.year&&a.month?a.month:1,t=m==l.year&&l.month?l.month:12;h.length>d&&(e=h[d],e.year==m&&d++);for(var r=1;12>=r;r++){if(r<p||r>t)k=document.createElement("DIV"),k.className="cell";else{var v=!1;g.length>c&&(f=g[c],f.year==m&&f.month==r&&(v=!0,c++));k=document.createElement("DIV");k.className=0<f.v?"cell blue":0>f.v?"cell red":"cell";k.innerHTML=v?(100*f.v).toFixed(10<
f.v?0:2)+"%":"-"}n.appendChild(k)}k=document.createElement("DIV");k.className=0<e.v?"cell total blue":0>e.v?"cell total red":"cell total";k.innerHTML=e.year>m?"-":(100*e.v).toFixed(10<e.v?0:2)+"%";n.appendChild(k)}}};var GlobalCounter;List=List||{};
List.RenderBalance=function(){if(user_login){var a=Localization.Get("balance_mql5")+" ",b=Localization.Get("do_deposit"),c=external.GetBalance()+" USD",d="https://www.mql5.com/"+Localization.GetDefaultLanguageMql5()+"/users/"+user_login+"/accounting/choosein",e=$("balance_in_list");if(e){e.innerHTML="";var f=document.createElement("A");f.innerHTML=a+c;f.href="#";f.onclick=function(a){external.OpenUrl(d);a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=!1};f.title=b;e.appendChild(f)}if(e=
$("balance_in_signal"))e.innerHTML="",f=document.createElement("A"),f.innerHTML=a+c,f.href="#",f.onclick=function(a){external.OpenUrl(d);a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=!1},f.title=b,e.appendChild(f);if(e=$("balance_in_statistics"))e.innerHTML="",f=document.createElement("A"),f.innerHTML=a+c,f.href="#",f.onclick=function(a){external.OpenUrl(d);a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=!1},f.title=b,e.appendChild(f)}};
List.RenderRegisterLink=function(){var a=Localization.Get("register_mql5"),b=Localization.GetTooltip("register_mql5"),c=function(){external.GetOptions()},d=$("balance_in_list");if(d){d.innerHTML="";var e=document.createElement("A");e.innerHTML=a;e.title=b;e.href="#";e.onclick=c;d.appendChild(e)}if(d=$("balance_in_signal"))d.innerHTML="",e=document.createElement("A"),e.innerHTML=a,e.title=b,e.href="#",e.onclick=c,d.appendChild(e);if(d=$("balance_in_statistics"))d.innerHTML="",e=document.createElement("A"),
e.innerHTML=a,e.title=b,e.href="#",e.onclick=c,d.appendChild(e)};Details.FillDetailsPlain=function(a,b){for(var c in b){var d=$(c);if(d){var e=b[c];if("string"==typeof e){var f=a[e];d.innerHTML=f||0==f?f:"["+e+"]"}else for(var g in e)(f=a[e[g]])||0==f||(f="["+e[g]+"]"),"_"==g?d.innerHTML=f:(d.setAttribute(g,""),d.setAttribute(g,f))}}};
Details.FillDetailsStatistics=function(a,b,c){for(var d in b){var e=$(d);if(e){var f=a[b[d]];if(f||0==f)switch(c){case "currency":e.innerHTML=Helpers.FormatThousands(f.toFixed(2));do e=e.nextSibling;while(!e||"VAR"!=e.tagName);e&&(e.innerHTML=a.currency);break;case "currency_colored":0<f?e.className="blue":0>f&&(e.className="red");e.innerHTML=Helpers.FormatThousands(f.toFixed(2));do e=e.nextSibling;while(!e||"VAR"!=e.tagName);e&&(e.innerHTML=a.currency);break;case "currency_colored_dd":0>f?e.className=
"blue":0<f&&(e.className="red");e.innerHTML=Helpers.FormatThousands(f.toFixed(2));do e=e.nextSibling;while(!e||"VAR"!=e.tagName);e&&(e.innerHTML=a.currency);break;case "percents":e.innerHTML=1E4<=f?Helpers.FormatThousands(Math.round(f))+"%":Helpers.FormatThousands(f.toFixed(2))+"%";break;case "percents_colored":0<f?e.className="blue":0>f&&(e.className="red");e.innerHTML=1E4<=f?Helpers.FormatThousands(Math.round(f))+"%":Helpers.FormatThousands(f.toFixed(2))+"%";break;case "percents_colored_raw":0<
f?e.className="blue":0>f&&(e.className="red");e.innerHTML=100<=f?Helpers.FormatThousands(Math.round(100*f))+"%":Helpers.FormatThousands((100*f).toFixed(2))+"%";break;case "percents_colored_dd":0>f?e.className="blue":0<f&&(e.className="red");e.innerHTML=1E4<=f?Helpers.FormatThousands(Math.round(f))+"%":Helpers.FormatThousands(f.toFixed(2))+"%";break;case "time":e.innerHTML=Helpers.FormatTimeElapsed(f);break;case "money":e.innerHTML=Helpers.FormatMoney(f);break;default:e.innerHTML=Helpers.FormatThousands(f||
0)}else e.innerHTML=0}}};function NotifyLoginChange(a,b){"GetVat"in external&&(b=parseFloat(external.GetVat()),vat!==b&&(vat=b,NotifySignals()));if(Details)if(Details.Current){b=Details.Current.id;Details.Reset();var c=document.getElementById("paymentSystemListBlock")?!0:!1,d=document.getElementById("paymentSystemMessageBlock")?!0:!1;Signals.Select(null,b,c,!1,d)}else Details.Existing&&Details.Reset();Signals.Ready&&((user_login=a)?List.RenderBalance():List.RenderRegisterLink())}
function NotifySignals(){Signals.Ready&&(Details.Hide(),Statistics.Hide(),List.SetSection(List.CurrentSection))}
function NotifySubscriptions(){if(Signals.Ready){Signals.InitAccount();Signals.InitSubscription();Statistics.Current&&Statistics.Show(Statistics.Current);if(Details.Current){var a=Details.Current.id,b=document.getElementById("paymentSystemListBlock"),c=document.getElementById("paymentSystemMessageBlock");b||c||(Details.Reset(),Signals.Select(null,a,!1,!1))}else Details.Existing&&Details.Reset();List.SetSection(List.CurrentSection);List.RenderBalance()}}
function ShowSignal(a,b){if(Signals.Preloading)return Signals.Preloading=!1,!0;if(0==a)return!1;b||(b=external.GetSignal(a,Details.GetChartWidth(),Details.GetChartHeight()));if(!b)return Details.Current=null,!1;a=jsonParse(b,11);if(!Signals.Ready)return Details.Current=a,!1;Signals.LoadingBar.Hide();Details.Show(a);return!0}
function ShowStatistics(a,b,c,d){d||(d=external.GetStatisticsDetail(a,b,c,Statistics.GetChartWidth(),Statistics.GetChartHeight()));if(!d)return!1;a=jsonParse(d,10);"dataError"in a&&(a.subscription={dataError:a.dataError});Statistics.Show(a.subscription);return!0}function NotifyReviewsNews(a){Signals.Ready&&Details.MoreNewsReviews(a)}function ClosePayWindow(){try{return Signals.PaymentSystem.ClosePayWindow()}catch(a){return errorsConsole.Add(a),!1}}
function setImgesSrcAsync(a){for(var b=[],c=0;c<a.length;c++){var d=a[c].image,e=a[c].src;if(d){var f=Helpers.GetHashIdByUrl(e);d.className=f}else{if(!a[c].imageName)continue;f=a[c].imageName}b[b.length]={url:e,id:f}}b.length&&(a=external.GetLocalPath(jsonStringify(b)),OnImagesDownloaded(a))}
function setImgesAvatarSrcAsync(a){for(var b=[],c=0;c<a.length;c++){var d=a[c].image,e=a[c].src;if(d){var f=Helpers.GetHashIdByUrl(e);d.className=f}else{if(!a[c].imageName)continue;f=a[c].imageName}b[b.length]={url:e,id:f}}b.length&&(a=jsonStringify(b),a="GetAvatarPath"in external?external.GetAvatarPath(a):external.GetLocalPath(a),OnImagesDownloaded(a))}
function OnImagesDownloaded(a){if(a&&a.length){if("string"==typeof a)return a=jsonParse(a,12),OnImagesDownloaded(a);for(var b=0,c=a.length;b<c;b++){var d=a[b].id,e=querySelectorAllFn(document,"."+d);if(e&&e.length)for(var f=a[b].path,g=0,h=e.length;g<h;g++)e[g].src=f,window.removeClass(e[g],d)}}}function PaymentSuccess(){try{return Signals.PaymentSystem.PaymentComplete(!0)}catch(a){return errorsConsole.Add(a),!1}}
function PaymentFailed(a){a=jsonParse(a,2);try{return Signals.PaymentSystem.PaymentComplete(!1,a)}catch(b){return errorsConsole.Add(b),!1}}function UnsubscribeConfirm(a){try{return Signals.Select(null,a,!1,!0)}catch(b){return errorsConsole.Add(b),!1}}function SubscribeConfirm(a){try{return Signals.Select(null,a,!0,!1)}catch(b){return errorsConsole.Add(b),!1}}function NotifyGetPaymentSystemsHtml(a){var b=document.getElementById("paymentList");b&&a&&(b.innerHTML=a)};
